export * from './lib/feature-inventory';
export * from './lib/components/ProductionMetricsCard';
export * from './lib/components/ResourceOptimizationPanel';
export * from './lib/components/InventoryDataGrid';
export * from './lib/components/InventoryForm';
export * from './lib/components/StockAdjustmentDialog';
export * from './lib/components/InventoryFilters';
export * from './lib/components/InventoryManagement';
export * from './lib/hooks/useInventory';
