/**
 * @fileoverview Mock bread products data
 * @module @bakery/shared/data-mocks/products
 */

import {
  Product,
  ProductCategory,
  ProductType,
  ProductStatus,
} from '@bakery/shared/types'

export const BREAD_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Kornbrot 500g',
    description:
      'Herzhaftes Vollkornbrot mit Sonnenblumenkernen und Leinsamen. Reich an Ballaststoffen und perfekt für ein gesundes Frühstück.',
    category: ProductCategory.Bread,
    type: ProductType.Fresh,
    image: '/assets/images/products/Type=Kornbrot.svg',
    price: 2.5,
    isActive: true,
    stock: 30,
    allergens: ['Gluten', 'Sesam'],
    ingredients: [
      'Vollkornmehl',
      'Roggenmehl',
      'Wasser',
      'Sauerteig',
      'Sonnenblumenkerne',
      'Leinsamen',
      'Salz',
      'Hefe',
    ],
    nutritionalInfo: {
      calories: 245,
      protein: 8.5,
      carbohydrates: 42,
      fat: 4.2,
      fiber: 7.5,
      sugar: 2.1,
    },
    weight: 500,
    unit: 'g',
    dailyTarget: 25,
    status: ProductStatus.Available,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    bakingTime: '06:00',
    shelfLife: 4,
  } as Product & { bakingTime: string; shelfLife: number },
  {
    id: 2,
    name: 'Kornbrot 1000g',
    description:
      'Unser beliebtes Vollkornbrot in der Familiengröße. Bleibt lange frisch und saftig.',
    category: ProductCategory.Bread,
    type: ProductType.Fresh,
    image: '/assets/images/products/Type=Kornbrot.svg',
    price: 4.4,
    isActive: true,
    stock: 20,
    allergens: ['Gluten', 'Sesam'],
    ingredients: [
      'Vollkornmehl',
      'Roggenmehl',
      'Wasser',
      'Sauerteig',
      'Sonnenblumenkerne',
      'Leinsamen',
      'Salz',
      'Hefe',
    ],
    nutritionalInfo: {
      calories: 245,
      protein: 8.5,
      carbohydrates: 42,
      fat: 4.2,
      fiber: 7.5,
      sugar: 2.1,
    },
    weight: 1000,
    unit: 'g',
    dailyTarget: 15,
    status: ProductStatus.Available,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    bakingTime: '06:00',
    shelfLife: 4,
  } as Product & { bakingTime: string; shelfLife: number },
  {
    id: 3,
    name: 'Mischbrot 500g',
    description:
      'Klassisches deutsches Mischbrot aus Weizen- und Roggenmehl. Mild im Geschmack und vielseitig verwendbar.',
    category: ProductCategory.Bread,
    type: ProductType.Fresh,
    image: '/assets/images/products/Type=Mischbrot.svg',
    price: 2.3,
    isActive: true,
    stock: 35,
    allergens: ['Gluten'],
    ingredients: [
      'Weizenmehl',
      'Roggenmehl',
      'Wasser',
      'Sauerteig',
      'Salz',
      'Hefe',
    ],
    nutritionalInfo: {
      calories: 235,
      protein: 7.2,
      carbohydrates: 45,
      fat: 1.5,
      fiber: 4.3,
      sugar: 2.8,
    },
    weight: 500,
    unit: 'g',
    dailyTarget: 30,
    status: ProductStatus.Available,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    bakingTime: '05:30',
    shelfLife: 3,
  } as Product & { bakingTime: string; shelfLife: number },
  {
    id: 4,
    name: 'Mischbrot 1000g',
    description:
      'Unser Mischbrot-Klassiker für die ganze Familie. Perfekt für Sandwiches und zum Frühstück.',
    category: ProductCategory.Bread,
    type: ProductType.Fresh,
    image: '/assets/images/products/Type=Mischbrot.svg',
    price: 4.0,
    isActive: true,
    stock: 25,
    allergens: ['Gluten'],
    ingredients: [
      'Weizenmehl',
      'Roggenmehl',
      'Wasser',
      'Sauerteig',
      'Salz',
      'Hefe',
    ],
    nutritionalInfo: {
      calories: 235,
      protein: 7.2,
      carbohydrates: 45,
      fat: 1.5,
      fiber: 4.3,
      sugar: 2.8,
    },
    weight: 1000,
    unit: 'g',
    dailyTarget: 20,
    status: ProductStatus.Available,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    bakingTime: '05:30',
    shelfLife: 3,
  } as Product & { bakingTime: string; shelfLife: number },
  {
    id: 5,
    name: 'Landbrot 750g',
    description:
      'Rustikales Bauernbrot mit kräftiger Kruste und saftigem Inneren. Nach traditionellem Rezept gebacken.',
    category: ProductCategory.Bread,
    type: ProductType.Fresh,
    image: '/assets/images/products/Type=Landbrot.svg',
    price: 3.5,
    isActive: true,
    stock: 28,
    allergens: ['Gluten'],
    ingredients: [
      'Roggenmehl',
      'Weizenmehl',
      'Wasser',
      'Natursauerteig',
      'Salz',
      'Brotgewürz',
    ],
    nutritionalInfo: {
      calories: 220,
      protein: 6.8,
      carbohydrates: 43,
      fat: 1.2,
      fiber: 5.5,
      sugar: 2.5,
    },
    weight: 750,
    unit: 'g',
    dailyTarget: 22,
    status: ProductStatus.Available,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    bakingTime: '05:00',
    shelfLife: 5,
  } as Product & { bakingTime: string; shelfLife: number },
  {
    id: 6,
    name: 'Roggenbrot 500g',
    description:
      'Kräftiges Roggenbrot mit charakteristischem Geschmack. Reich an Mineralstoffen und besonders bekömmlich.',
    category: ProductCategory.Bread,
    type: ProductType.Fresh,
    image: '/assets/images/products/Type=Roggenbrot.svg',
    price: 2.8,
    isActive: true,
    stock: 20,
    allergens: ['Gluten'],
    ingredients: [
      'Roggenvollkornmehl',
      'Wasser',
      'Natursauerteig',
      'Salz',
      'Kümmel',
    ],
    nutritionalInfo: {
      calories: 210,
      protein: 6.5,
      carbohydrates: 41,
      fat: 1.0,
      fiber: 8.2,
      sugar: 2.0,
    },
    weight: 500,
    unit: 'g',
    dailyTarget: 18,
    status: ProductStatus.Available,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    bakingTime: '04:30',
    shelfLife: 6,
  } as Product & { bakingTime: string; shelfLife: number },
  {
    id: 7,
    name: 'Dinkelbrot 500g',
    description:
      'Bekömmliches Brot aus reinem Dinkelmehl. Nussiger Geschmack und besonders verträglich.',
    category: ProductCategory.Bread,
    type: ProductType.Fresh,
    image: '/assets/images/products/Type=Dinkelbrot.svg',
    price: 3.2,
    isActive: true,
    stock: 15,
    allergens: ['Gluten'],
    ingredients: [
      'Dinkelvollkornmehl',
      'Wasser',
      'Dinkelsauerteig',
      'Meersalz',
      'Hefe',
    ],
    nutritionalInfo: {
      calories: 238,
      protein: 9.0,
      carbohydrates: 44,
      fat: 2.4,
      fiber: 6.8,
      sugar: 2.3,
    },
    weight: 500,
    unit: 'g',
    dailyTarget: 15,
    status: ProductStatus.Available,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    bakingTime: '06:30',
    shelfLife: 3,
  } as Product & { bakingTime: string; shelfLife: number },
]
