/**
 * @fileoverview Mock bun products data
 * @module @bakery/shared/data-mocks/products
 */

import {
  Product,
  ProductCategory,
  ProductType,
  ProductStatus,
} from '@bakery/shared/types'

export const BUN_PRODUCTS: Product[] = [
  {
    id: 8,
    name: 'Brötchen',
    description:
      'Klassische deutsche Frühstücksbrötchen. Knusprig außen, fluffig innen.',
    category: ProductCategory.Buns,
    type: ProductType.Fresh,
    image: '/assets/images/products/Type=Broetchen.svg',
    price: 0.45,
    isActive: true,
    stock: 120,
    allergens: ['Gluten'],
    ingredients: ['Weizenmehl', 'Wasser', 'Hefe', 'Salz', 'Malz', 'Zucker'],
    nutritionalInfo: {
      calories: 152,
      protein: 5.2,
      carbohydrates: 30,
      fat: 1.1,
      fiber: 1.8,
      sugar: 2.5,
    },
    weight: 60,
    unit: 'Stück',
    dailyTarget: 100,
    status: ProductStatus.Available,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    bakingTime: '04:00',
    shelfLife: 1,
  } as Product & { bakingTime: string; shelfLife: number },
  {
    id: 9,
    name: 'Laugenbrötchen',
    description:
      'Traditionelle bayerische Laugenbrötchen mit grobem Salz bestreut.',
    category: ProductCategory.Buns,
    type: ProductType.Fresh,
    image: '/assets/images/products/Type=Laugenbroetchen.svg',
    price: 0.75,
    isActive: true,
    stock: 80,
    allergens: ['Gluten'],
    ingredients: [
      'Weizenmehl',
      'Wasser',
      'Hefe',
      'Salz',
      'Natronlauge',
      'Grobes Salz',
    ],
    nutritionalInfo: {
      calories: 165,
      protein: 5.8,
      carbohydrates: 32,
      fat: 1.5,
      fiber: 1.5,
      sugar: 2.0,
    },
    weight: 70,
    unit: 'Stück',
    dailyTarget: 60,
    status: ProductStatus.Available,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    bakingTime: '04:30',
    shelfLife: 1,
  } as Product & { bakingTime: string; shelfLife: number },
  {
    id: 10,
    name: 'Kürbiskernbrötchen',
    description:
      'Vollkornbrötchen mit knackigen Kürbiskernen. Reich an Omega-3-Fettsäuren.',
    category: ProductCategory.Buns,
    type: ProductType.Fresh,
    image: '/assets/images/products/Type=Kuerbiskernbroetchen.svg',
    price: 0.95,
    isActive: true,
    stock: 50,
    allergens: ['Gluten', 'Kürbiskerne'],
    ingredients: [
      'Vollkornmehl',
      'Wasser',
      'Kürbiskerne',
      'Hefe',
      'Salz',
      'Malz',
    ],
    nutritionalInfo: {
      calories: 178,
      protein: 7.2,
      carbohydrates: 28,
      fat: 4.5,
      fiber: 3.8,
      sugar: 2.2,
    },
    weight: 75,
    unit: 'Stück',
    dailyTarget: 40,
    status: ProductStatus.Available,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    bakingTime: '04:30',
    shelfLife: 2,
  } as Product & { bakingTime: string; shelfLife: number },
  {
    id: 11,
    name: 'Körnerbrötchen',
    description:
      'Rustikale Brötchen mit Sonnenblumenkernen, Leinsamen und Sesam.',
    category: ProductCategory.Buns,
    type: ProductType.Fresh,
    image: '/assets/images/products/Type=Koernerbroetchen.svg',
    price: 0.85,
    isActive: true,
    stock: 60,
    allergens: ['Gluten', 'Sesam'],
    ingredients: [
      'Weizenmehl',
      'Roggenmehl',
      'Wasser',
      'Sonnenblumenkerne',
      'Leinsamen',
      'Sesam',
      'Hefe',
      'Salz',
    ],
    nutritionalInfo: {
      calories: 172,
      protein: 6.5,
      carbohydrates: 29,
      fat: 3.8,
      fiber: 3.2,
      sugar: 2.3,
    },
    weight: 70,
    unit: 'Stück',
    dailyTarget: 50,
    status: ProductStatus.Available,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    bakingTime: '04:30',
    shelfLife: 2,
  } as Product & { bakingTime: string; shelfLife: number },
  {
    id: 12,
    name: 'Milchbrötchen',
    description:
      'Weiche, süßliche Brötchen mit Milch gebacken. Perfekt für Kinder.',
    category: ProductCategory.Buns,
    type: ProductType.Fresh,
    image: '/assets/images/products/Type=Milchbroetchen.svg',
    price: 0.65,
    isActive: true,
    stock: 70,
    allergens: ['Gluten', 'Milch', 'Ei'],
    ingredients: [
      'Weizenmehl',
      'Milch',
      'Butter',
      'Zucker',
      'Ei',
      'Hefe',
      'Salz',
    ],
    nutritionalInfo: {
      calories: 185,
      protein: 6.0,
      carbohydrates: 32,
      fat: 4.2,
      fiber: 1.2,
      sugar: 5.5,
    },
    weight: 65,
    unit: 'Stück',
    dailyTarget: 60,
    status: ProductStatus.Available,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    bakingTime: '05:00',
    shelfLife: 2,
  } as Product & { bakingTime: string; shelfLife: number },
  {
    id: 13,
    name: 'Mehrkornbrötchen',
    description:
      '7-Korn-Brötchen mit wertvollen Ballaststoffen und Mineralstoffen.',
    category: ProductCategory.Buns,
    type: ProductType.Fresh,
    image: '/assets/images/products/Type=Mehrkornbroetchen.svg',
    price: 0.9,
    isActive: true,
    stock: 55,
    allergens: ['Gluten', 'Sesam', 'Soja'],
    ingredients: [
      'Weizenmehl',
      'Roggenmehl',
      'Haferflocken',
      'Leinsamen',
      'Sonnenblumenkerne',
      'Sesam',
      'Hirse',
      'Buchweizen',
      'Wasser',
      'Hefe',
      'Salz',
    ],
    nutritionalInfo: {
      calories: 168,
      protein: 6.8,
      carbohydrates: 27,
      fat: 3.5,
      fiber: 4.2,
      sugar: 2.0,
    },
    weight: 75,
    unit: 'Stück',
    dailyTarget: 45,
    status: ProductStatus.Available,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    bakingTime: '04:45',
    shelfLife: 2,
  } as Product & { bakingTime: string; shelfLife: number },
  {
    id: 14,
    name: 'Croissant',
    description:
      'Französisches Buttergebäck, luftig und blättrig. Ein Hauch von Paris.',
    category: ProductCategory.Buns,
    type: ProductType.Fresh,
    image: '/assets/images/products/Type=Croissant.svg',
    price: 1.5,
    isActive: true,
    stock: 40,
    allergens: ['Gluten', 'Milch', 'Ei'],
    ingredients: [
      'Weizenmehl',
      'Butter',
      'Milch',
      'Zucker',
      'Ei',
      'Hefe',
      'Salz',
    ],
    nutritionalInfo: {
      calories: 231,
      protein: 4.8,
      carbohydrates: 26,
      fat: 12.5,
      fiber: 1.0,
      sugar: 4.5,
    },
    weight: 55,
    unit: 'Stück',
    dailyTarget: 35,
    status: ProductStatus.Available,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    bakingTime: '05:30',
    shelfLife: 1,
  } as Product & { bakingTime: string; shelfLife: number },
  {
    id: 15,
    name: 'Laugencroissant',
    description:
      'Die perfekte Fusion: Französisches Croissant trifft auf bayerische Laugenbrezel.',
    category: ProductCategory.Buns,
    type: ProductType.Fresh,
    image: '/assets/images/products/Type=Laugencroissant.svg',
    price: 1.8,
    isActive: true,
    stock: 30,
    allergens: ['Gluten', 'Milch', 'Ei'],
    ingredients: [
      'Weizenmehl',
      'Butter',
      'Milch',
      'Natronlauge',
      'Grobes Salz',
      'Zucker',
      'Ei',
      'Hefe',
    ],
    nutritionalInfo: {
      calories: 242,
      protein: 5.2,
      carbohydrates: 27,
      fat: 13.0,
      fiber: 1.1,
      sugar: 3.8,
    },
    weight: 60,
    unit: 'Stück',
    dailyTarget: 25,
    status: ProductStatus.Available,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    bakingTime: '06:00',
    shelfLife: 1,
  } as Product & { bakingTime: string; shelfLife: number },
]
