/**
 * @fileoverview Mock cake and pastry products data
 * @module @bakery/shared/data-mocks/products
 */

import { Product } from '@bakery/shared/types'

export const CAKE_PRODUCTS: Product[] = [
  {
    id: 16,
    name: 'Apfelkuchen',
    description:
      'Traditioneller deutscher Apfelkuchen mit frischen Äpfeln und Zimt. Nach Omas Rezept.',
    category: 'Kuchen',
    type: 'cake',
    image: '/assets/images/products/Type=Apfelkuchen.svg',
    price: 2.8,
    isActive: true,
    stock: 12,
    allergens: ['Gluten', 'Milch', 'Ei'],
    ingredients: [
      'Weizenmehl',
      'Äpfel',
      'Zucker',
      'Butter',
      'Eier',
      'Zimt',
      'Backpulver',
      'Vanille',
    ],
    nutritionalInfo: {
      calories: 285,
      protein: 3.5,
      carbs: 42,
      fat: 12.0,
      fiber: 2.1,
      sugar: 24,
    },
    weight: 120,
    unit: 'Stück',
    dailyTarget: 10,
    bakingTime: '07:00',
    shelfLife: 3,
  },
  {
    id: 17,
    name: 'Käsekuchen',
    description:
      'Cremiger Käsekuchen mit Quark auf knusprigem Mürbeteigboden. Ein Klassiker!',
    category: 'Kuchen',
    type: 'cake',
    image: '/assets/images/products/Type=Kaesekuchen.svg',
    price: 3.2,
    isActive: true,
    stock: 10,
    allergens: ['Gluten', 'Milch', 'Ei'],
    ingredients: [
      'Quark',
      'Weizenmehl',
      'Zucker',
      'Butter',
      'Eier',
      'Vanille',
      'Zitrone',
    ],
    nutritionalInfo: {
      calories: 320,
      protein: 8.5,
      carbs: 35,
      fat: 16.5,
      fiber: 0.8,
      sugar: 22,
    },
    weight: 130,
    unit: 'Stück',
    dailyTarget: 8,
    bakingTime: '07:30',
    shelfLife: 4,
  },
  {
    id: 18,
    name: 'Schwarzwälder Kirschtorte',
    description:
      'Die weltberühmte Torte mit Kirschen, Sahne und einem Hauch Kirschwasser.',
    category: 'Torte',
    type: 'cake',
    image: '/assets/images/products/Type=Schwarzwaelder.svg',
    price: 4.5,
    isActive: true,
    stock: 6,
    allergens: ['Gluten', 'Milch', 'Ei', 'Alkohol'],
    ingredients: [
      'Schokoladenbiskuit',
      'Kirschen',
      'Sahne',
      'Zucker',
      'Kirschwasser',
      'Schokoladenraspel',
    ],
    nutritionalInfo: {
      calories: 385,
      protein: 4.2,
      carbs: 38,
      fat: 24.5,
      fiber: 2.5,
      sugar: 28,
    },
    weight: 150,
    unit: 'Stück',
    dailyTarget: 5,
    bakingTime: '08:00',
    shelfLife: 2,
  },
  {
    id: 19,
    name: 'Erdbeertorte',
    description:
      'Frische Erdbeertorte mit Vanillecreme und knusprigem Biskuitboden.',
    category: 'Torte',
    type: 'cake',
    image: '/assets/images/products/Type=Erdbeertorte.svg',
    price: 3.8,
    isActive: true,
    stock: 8,
    allergens: ['Gluten', 'Milch', 'Ei'],
    ingredients: [
      'Biskuitboden',
      'Erdbeeren',
      'Vanillecreme',
      'Sahne',
      'Zucker',
      'Gelatine',
    ],
    nutritionalInfo: {
      calories: 265,
      protein: 3.8,
      carbs: 35,
      fat: 12.8,
      fiber: 1.8,
      sugar: 25,
    },
    weight: 140,
    unit: 'Stück',
    dailyTarget: 6,
    bakingTime: '06:30',
    shelfLife: 1,
  },
  {
    id: 20,
    name: 'Pflaumenkuchen',
    description:
      'Saftiger Pflaumenkuchen mit Streuseln. Perfekt zur Pflaumenzeit im Spätsommer.',
    category: 'Kuchen',
    type: 'cake',
    image: '/assets/images/products/Type=Pflaumenkuchen.svg',
    price: 2.6,
    isActive: true,
    stock: 14,
    allergens: ['Gluten', 'Milch', 'Ei'],
    ingredients: [
      'Weizenmehl',
      'Pflaumen',
      'Zucker',
      'Butter',
      'Eier',
      'Streusel',
      'Zimt',
    ],
    nutritionalInfo: {
      calories: 275,
      protein: 3.2,
      carbs: 40,
      fat: 11.5,
      fiber: 2.8,
      sugar: 23,
    },
    weight: 125,
    unit: 'Stück',
    dailyTarget: 12,
    bakingTime: '07:00',
    shelfLife: 2,
  },
  {
    id: 21,
    name: 'Marmorkuchen',
    description:
      'Klassischer Marmorkuchen mit Schokoladen- und Vanilleteig marmoriert.',
    category: 'Kuchen',
    type: 'cake',
    image: '/assets/images/products/Type=Marmorkuchen.svg',
    price: 2.4,
    isActive: true,
    stock: 16,
    allergens: ['Gluten', 'Milch', 'Ei'],
    ingredients: [
      'Weizenmehl',
      'Zucker',
      'Butter',
      'Eier',
      'Kakao',
      'Vanille',
      'Backpulver',
    ],
    nutritionalInfo: {
      calories: 295,
      protein: 4.5,
      carbs: 38,
      fat: 14.5,
      fiber: 1.5,
      sugar: 20,
    },
    weight: 110,
    unit: 'Stück',
    dailyTarget: 14,
    bakingTime: '06:30',
    shelfLife: 4,
  },
  {
    id: 22,
    name: 'Bienenstich',
    description:
      'Hefekuchen mit Vanillecreme-Füllung und karamellisierten Mandeln.',
    category: 'Kuchen',
    type: 'cake',
    image: '/assets/images/products/Type=Bienenstich.svg',
    price: 3.4,
    isActive: true,
    stock: 10,
    allergens: ['Gluten', 'Milch', 'Ei', 'Mandeln'],
    ingredients: [
      'Hefeteig',
      'Vanillecreme',
      'Mandeln',
      'Honig',
      'Zucker',
      'Butter',
    ],
    nutritionalInfo: {
      calories: 342,
      protein: 5.8,
      carbs: 36,
      fat: 19.5,
      fiber: 2.2,
      sugar: 24,
    },
    weight: 135,
    unit: 'Stück',
    dailyTarget: 8,
    bakingTime: '08:00',
    shelfLife: 2,
  },
  {
    id: 23,
    name: 'Nusskuchen',
    description:
      'Saftiger Nusskuchen mit gemahlenen Haselnüssen und Schokoladenglasur.',
    category: 'Kuchen',
    type: 'cake',
    image: '/assets/images/products/Type=Nusskuchen.svg',
    price: 3.0,
    isActive: true,
    stock: 12,
    allergens: ['Gluten', 'Milch', 'Ei', 'Haselnüsse'],
    ingredients: [
      'Weizenmehl',
      'Haselnüsse',
      'Zucker',
      'Butter',
      'Eier',
      'Schokolade',
      'Backpulver',
    ],
    nutritionalInfo: {
      calories: 365,
      protein: 6.5,
      carbs: 35,
      fat: 22.5,
      fiber: 3.5,
      sugar: 22,
    },
    weight: 120,
    unit: 'Stück',
    dailyTarget: 10,
    bakingTime: '07:00',
    shelfLife: 5,
  },
]
