/**
 * @fileoverview Mock snack and special products data
 * @module @bakery/shared/data-mocks/products
 */

import { Product } from '@bakery/shared/types'

export const SNACK_PRODUCTS: Product[] = [
  {
    id: 24,
    name: 'Brezel',
    description:
      'Original bayerische Laugenbrezel mit grobem Salz. Knusprig und salzig.',
    category: 'Snacks',
    type: 'snack',
    image: '/assets/images/products/Type=Brezel.svg',
    price: 1.2,
    isActive: true,
    stock: 60,
    allergens: ['Gluten'],
    ingredients: [
      'Weizenmehl',
      'Wasser',
      'Hefe',
      'Salz',
      'Natronlauge',
      'Grobes Salz',
    ],
    nutritionalInfo: {
      calories: 218,
      protein: 7.5,
      carbs: 42,
      fat: 2.1,
      fiber: 1.8,
      sugar: 2.5,
    },
    weight: 85,
    unit: 'Stück',
    dailyTarget: 50,
    bakingTime: '05:00',
    shelfLife: 1,
  },
  {
    id: 25,
    name: 'Käsebrezel',
    description:
      'Laugenbrezel mit würzigem Käse überbacken. Der herzhafte Snack.',
    category: 'Snacks',
    type: 'snack',
    image: '/assets/images/products/Type=Kaesebrezel.svg',
    price: 2.2,
    isActive: true,
    stock: 30,
    allergens: ['Gluten', 'Milch'],
    ingredients: [
      'Weizenmehl',
      'Wasser',
      'Hefe',
      'Salz',
      'Natronlauge',
      'Emmentaler',
      'Gouda',
    ],
    nutritionalInfo: {
      calories: 315,
      protein: 12.5,
      carbs: 42,
      fat: 11.5,
      fiber: 1.8,
      sugar: 2.5,
    },
    weight: 110,
    unit: 'Stück',
    dailyTarget: 25,
    bakingTime: '05:30',
    shelfLife: 1,
  },
  {
    id: 26,
    name: 'Pizzabrötchen',
    description:
      'Mini-Pizzabrötchen mit Tomaten, Käse und italienischen Kräutern.',
    category: 'Snacks',
    type: 'snack',
    image: '/assets/images/products/Type=Pizzabroetchen.svg',
    price: 1.8,
    isActive: true,
    stock: 40,
    allergens: ['Gluten', 'Milch'],
    ingredients: [
      'Weizenmehl',
      'Tomatensauce',
      'Mozzarella',
      'Oregano',
      'Basilikum',
      'Olivenöl',
    ],
    nutritionalInfo: {
      calories: 245,
      protein: 8.5,
      carbs: 32,
      fat: 9.5,
      fiber: 2.1,
      sugar: 3.5,
    },
    weight: 90,
    unit: 'Stück',
    dailyTarget: 35,
    bakingTime: '05:30',
    shelfLife: 1,
  },
  {
    id: 27,
    name: 'Schokocroissant',
    description:
      'Buttercroissant gefüllt mit feinster Schokolade. Ein Genuss zum Frühstück.',
    category: 'Gebäck',
    type: 'pastry',
    image: '/assets/images/products/Type=Schokocroissant.svg',
    price: 1.9,
    isActive: true,
    stock: 35,
    allergens: ['Gluten', 'Milch', 'Ei', 'Soja'],
    ingredients: [
      'Weizenmehl',
      'Butter',
      'Schokolade',
      'Milch',
      'Zucker',
      'Ei',
      'Hefe',
    ],
    nutritionalInfo: {
      calories: 295,
      protein: 5.2,
      carbs: 32,
      fat: 16.5,
      fiber: 2.5,
      sugar: 12,
    },
    weight: 75,
    unit: 'Stück',
    dailyTarget: 30,
    bakingTime: '06:00',
    shelfLife: 2,
  },
  {
    id: 28,
    name: 'Nussschnecke',
    description:
      'Hefeteig-Schnecke mit Nussfüllung und Zuckerguss. Süß und nussig.',
    category: 'Gebäck',
    type: 'pastry',
    image: '/assets/images/products/Type=Nussschnecke.svg',
    price: 2.4,
    isActive: true,
    stock: 25,
    allergens: ['Gluten', 'Milch', 'Ei', 'Haselnüsse', 'Walnüsse'],
    ingredients: [
      'Hefeteig',
      'Haselnüsse',
      'Walnüsse',
      'Zucker',
      'Zimt',
      'Butter',
      'Zuckerguss',
    ],
    nutritionalInfo: {
      calories: 385,
      protein: 7.5,
      carbs: 45,
      fat: 20.5,
      fiber: 3.2,
      sugar: 25,
    },
    weight: 110,
    unit: 'Stück',
    dailyTarget: 20,
    bakingTime: '06:30',
    shelfLife: 3,
  },
  {
    id: 29,
    name: 'Donut Glasur',
    description:
      'Amerikanischer Donut mit bunter Glasur und Streuseln. Der Klassiker!',
    category: 'Gebäck',
    type: 'pastry',
    image: '/assets/images/products/Type=Donut.svg',
    price: 2.2,
    isActive: true,
    stock: 30,
    allergens: ['Gluten', 'Milch', 'Ei'],
    ingredients: [
      'Weizenmehl',
      'Zucker',
      'Butter',
      'Eier',
      'Hefe',
      'Glasur',
      'Streusel',
    ],
    nutritionalInfo: {
      calories: 425,
      protein: 4.8,
      carbs: 52,
      fat: 22.5,
      fiber: 1.5,
      sugar: 32,
    },
    weight: 95,
    unit: 'Stück',
    dailyTarget: 25,
    bakingTime: '05:00',
    shelfLife: 2,
  },
  {
    id: 30,
    name: 'Berliner',
    description:
      'Traditioneller Berliner Pfannkuchen mit Marmeladenfüllung und Puderzucker.',
    category: 'Gebäck',
    type: 'pastry',
    image: '/assets/images/products/Type=Berliner.svg',
    price: 1.6,
    isActive: true,
    stock: 40,
    allergens: ['Gluten', 'Milch', 'Ei'],
    ingredients: [
      'Weizenmehl',
      'Milch',
      'Butter',
      'Eier',
      'Zucker',
      'Hefe',
      'Marmelade',
      'Puderzucker',
    ],
    nutritionalInfo: {
      calories: 315,
      protein: 5.5,
      carbs: 42,
      fat: 14.5,
      fiber: 1.2,
      sugar: 18,
    },
    weight: 85,
    unit: 'Stück',
    dailyTarget: 35,
    bakingTime: '05:30',
    shelfLife: 1,
  },
  {
    id: 31,
    name: 'Quarktasche',
    description:
      'Blätterteig gefüllt mit süßer Quarkcreme. Luftig und cremig zugleich.',
    category: 'Gebäck',
    type: 'pastry',
    image: '/assets/images/products/Type=Quarktasche.svg',
    price: 2.0,
    isActive: true,
    stock: 28,
    allergens: ['Gluten', 'Milch', 'Ei'],
    ingredients: ['Blätterteig', 'Quark', 'Zucker', 'Vanille', 'Ei', 'Rosinen'],
    nutritionalInfo: {
      calories: 285,
      protein: 7.2,
      carbs: 32,
      fat: 14.8,
      fiber: 0.8,
      sugar: 15,
    },
    weight: 100,
    unit: 'Stück',
    dailyTarget: 25,
    bakingTime: '06:00',
    shelfLife: 2,
  },
  {
    id: 32,
    name: 'Lebkuchen',
    description:
      'Würziger Lebkuchen mit Honig und Gewürzen. Besonders zur Weihnachtszeit.',
    category: 'Gebäck',
    type: 'seasonal',
    image: '/assets/images/products/Type=Lebkuchen.svg',
    price: 1.4,
    isActive: false, // Seasonal item
    stock: 0,
    allergens: ['Gluten', 'Ei', 'Mandeln'],
    ingredients: [
      'Weizenmehl',
      'Honig',
      'Zucker',
      'Eier',
      'Lebkuchengewürz',
      'Mandeln',
      'Zitronat',
    ],
    nutritionalInfo: {
      calories: 380,
      protein: 5.8,
      carbs: 68,
      fat: 10.5,
      fiber: 2.8,
      sugar: 45,
    },
    weight: 100,
    unit: 'Stück',
    dailyTarget: 40,
    bakingTime: '07:00',
    shelfLife: 14,
  },
  {
    id: 33,
    name: 'Stollen',
    description:
      'Traditioneller Christstollen mit Trockenfrüchten, Marzipan und Puderzucker.',
    category: 'Gebäck',
    type: 'seasonal',
    image: '/assets/images/products/Type=Stollen.svg',
    price: 12.5,
    isActive: false, // Seasonal item
    stock: 0,
    allergens: ['Gluten', 'Milch', 'Ei', 'Mandeln'],
    ingredients: [
      'Weizenmehl',
      'Butter',
      'Rosinen',
      'Sultaninen',
      'Zitronat',
      'Orangeat',
      'Marzipan',
      'Mandeln',
      'Rum',
    ],
    nutritionalInfo: {
      calories: 425,
      protein: 5.2,
      carbs: 58,
      fat: 19.5,
      fiber: 2.5,
      sugar: 38,
    },
    weight: 1000,
    unit: 'g',
    dailyTarget: 10,
    bakingTime: '08:00',
    shelfLife: 30,
  },
]
